name: install

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}

  update:
    needs: meta
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: update
        shell: bash
        run: |
          mkdir -p ./update
          rsync -av --exclude='MaaCommonAssets' ./assets/ ./update/


      - uses: actions/upload-artifact@v4
        with:
          name: update
          path: "update"

  windows:
    needs: meta
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-win-${{ matrix.arch }}*"
          latest: true
          #version: "tag"
          #tag: "v2.4.2"  # 在这里指定 MaaFramework 的版本号
          out-file-path: "deps"
          extract: true

      - name: Download MFAWPF
        uses: robinraju/release-downloader@v1
        with:
          repository: SweetSmellFox/MFAWPF
          filename: MFAWPF*
          latest: true
          #version: "tag"
          #tag: "v1.2.3.8"  # 在这里指定 MFAWPF 的版本号
          out-file-path: MFA
          extract: true

      - name: Install
        shell: bash
        run: |
          python ./install.py ${{ needs.meta.outputs.tag }}
          cp ./MFA/MFAWPF.exe ./install
          # url项示例  https://github.com/SweetSmellFox/MFAWPF
          jq --arg version_name "MaaPcrclanbattle" --arg url ""https://github.com/yinju86/MaaPcrclanbattle"" --arg version ${{ needs.meta.outputs.tag }} '. + {"name": $version_name, "url": $url,"version": $version}' ./assets/interface.json > ./install/interface.json
          pip install pyinstaller
          pip install -r assets/requirements.txt
          pyinstaller --onefile -w --icon=assets/resource/kyouka.ico generator.py
          cp ./dist/generator.exe ./install
      - uses: actions/upload-artifact@v4
        with:
          name: MaaPcrclanbattle-win-${{ matrix.arch }}
          path: "install"


  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets

      - run: |
          cd assets
          for f in *; do
            (cd $f && zip -r ../$f-${{ needs.meta.outputs.tag }}.zip .)
          done
      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}